from copy import deepcopy
from pathlib import Path

from docx import Document
from docx.oxml import OxmlElement
from docx.text.paragraph import Paragraph


DOC_PATH = Path("毕业论文") / "天津商业大学毕业设计(论文)张正豪v4.1-内容重做版.docx"


def insert_paragraph_after(paragraph: Paragraph, text: str = "", style=None) -> Paragraph:
    new_p = OxmlElement("w:p")
    paragraph._p.addnext(new_p)
    new_para = Paragraph(new_p, paragraph._parent)
    if style is not None:
        new_para.style = style
    if text:
        new_para.text = text
    return new_para


def fill_table(table, rows: list[list[str]]) -> None:
    row_count = len(table.rows)
    col_count = len(table.columns)
    for r_idx in range(row_count):
        values = rows[r_idx] if r_idx < len(rows) else [""] * col_count
        values = values + [""] * (col_count - len(values))
        for c_idx in range(col_count):
            table.cell(r_idx, c_idx).text = values[c_idx]


def main() -> None:
    doc = Document(str(DOC_PATH))

    # 4.2.2 需要补一段正文，先插入，再处理其后的段落索引
    anchor = doc.paragraphs[245]
    anchor.text = "4.2.2  社区加入与后台审核治理流程设计"
    inserted = insert_paragraph_after(
        anchor,
        "用户注册后先处于未加入社区状态，可通过邀请码提交社区加入申请。后台审核通过后，系统写入用户 community_id 并更新加入状态，后续公告、便民信息、公益需求、服务记录及治理数据均按所属社区隔离展示，从而同时保证居民归属真实性和社区治理的数据边界。",
        style=doc.paragraphs[239].style,
    )
    _ = inserted

    def mapped(idx: int) -> int:
        return idx if idx <= 245 else idx + 1

    para_updates = {
        44: "2.3 Vue 3、Naive UI与NutUI\t7",
        64: "随着我国人口老龄化程度加深和基层治理数字化转型的推进，社区公益服务面临供需错配、响应滞后和过程难追溯等突出问题。本文设计并实现了一套社区公益服务对接管理平台，围绕“社区加入—需求发布—审核流转—志愿者认领—服务完成—评价反馈—异常预警”构建社区互助闭环。",
        65: "系统采用前后端分离架构，后端基于 Spring Boot 3 提供 RESTful API，并结合 MyBatis-Plus 与 MySQL 8 完成业务持久化；管理端基于 Vue 3 与 Naive UI 构建，移动端基于 Vue 3 与 NutUI 开发。系统实现了统一账号、多角色权限、community_id 数据隔离、社区加入审核、志愿者认证、重点关怀对象管理、社区公告与便民信息、异常预警和审计日志等功能，AI 助手用于辅助整理求助信息。",
        66: "系统能够提升社区公益需求的发现效率、服务过程可追溯性和后台治理能力，为基层社区在助老、助残、陪诊等微服务场景中的数字化协同提供了可落地方案。",
        68: "关键词：社区公益服务；社区治理；志愿者认证；异常预警；Spring Boot 3；Vue 3",
        71: "The system adopts a front-end and back-end separation architecture. The back end is built with Spring Boot 3, MyBatis-Plus, and MySQL 8, while the administration side is developed with Vue 3 and Naive UI and the mobile side is developed with Vue 3 and NutUI. The platform supports unified accounts, role-based permissions, community-scoped data isolation, community join review, volunteer certification, care-subject management, announcements, convenience information, anomaly alerts, and audit logs. The AI assistant is positioned as an auxiliary tool for drafting service requests.",
        75: "Key Words: Community Public Welfare Service; Community Governance; Volunteer Certification; Anomaly Alert; Spring Boot 3; Vue 3",
        85: "本课题旨在设计并实现一套基于 Spring Boot 3 与 Vue 3 的社区公益服务对接管理平台，重点解决社区求助信息分散、审核链路缺失和服务数据难沉淀的问题。",
        86: "在理论层面，本文尝试将社区治理、公益互助和数字化流程管理结合起来，探索基层治理中“服务发现—服务执行—服务留痕—服务治理”的闭环设计思路。在实践层面，系统通过统一账号、社区绑定、审核留痕和评价反馈等机制，将居民求助、志愿服务和后台治理连接起来，并为重点关怀对象识别、异常预警处理和社区服务资源统筹提供技术支撑。",
        94: "本课题响应基层社会治理数字化建设需求，围绕社区公益服务中供需错配、服务流程割裂和数据治理薄弱等痛点，基于 Spring Boot 3 与 Vue 3 设计并开发一套面向真实社区场景的公益服务对接管理平台。系统的研究目标主要包括：",
        95: "1、构建社区公益服务闭环：围绕“居民发布求助—管理员审核—志愿者认领—服务完成—评价反馈”建立标准化流程，实现全过程状态可见、记录可追溯。",
        96: "2、建立统一账号与社区边界：用户注册后通过社区加入审核完成归属绑定，系统以 community_id 为核心实现公告、需求、服务记录和后台治理数据的社区隔离。",
        97: "3、增强治理支撑能力：在基础业务之外补充志愿者认证、重点关怀对象管理、便民信息维护、异常预警和数据看板，为社区管理者提供主动治理依据。",
        100: "1. 基于统一账号体系的用户与权限设计。系统采用 RBAC 角色访问控制模型，划分超级管理员、社区管理员和普通用户三类角色；普通用户在移动端默认以居民身份使用系统，经认证后扩展志愿服务能力，而非拆分为两套独立账号体系。",
        101: "权限隔离方面，超级管理员负责平台级配置与全局治理，社区管理员负责辖区内的社区加入审核、需求审核、志愿者审核和重点对象管理，普通用户则围绕求助发布、服务参与和结果反馈开展操作。",
        103: "2. 社区公益服务核心业务流转机制。该部分重点解决“谁需要帮助、谁可以提供帮助、过程如何被治理”的问题。",
        104: "需求标准化采集与审核：系统通过结构化表单采集服务类型、紧急程度、联系人和特殊标签等信息，并引入社区管理员审核机制，保证公益需求的真实性、合规性和社区归属准确性。",
        105: "志愿者认证与服务认领：用户提交志愿者认证资料后进入审核流程；认证通过后即可浏览需求列表、认领任务并更新服务进度，平台同时记录技能、服务半径、可服务时间和评价结果等信息。",
        107: "3. 基于数据沉淀的看板分析与异常预警。系统不仅展示需求数量、完成率和活跃志愿者等指标，还围绕重点关怀对象和异常事件生成后台治理信号。",
        108: "重点关怀与预警联动：通过重点关怀对象档案、服务记录、登录行为和紧急求助等数据，形成可供社区管理员跟进的异常预警事件，为后续回访和主动关怀提供依据。",
        116: "导言。主要介绍社区公益服务对接管理平台的研究背景与意义，梳理国内外相关研究现状，并说明本文的研究目标、研究内容和研究方法。",
        117: "介绍系统开发工具。本章说明本项目采用的主要技术与工具，包括 VS Code、Spring Boot 3、Vue 3、MyBatis-Plus、MySQL 8、Naive UI、NutUI 等，并分析其在本系统中的适用性。",
        118: "社区公益服务对接管理平台的规划与分析。本章介绍系统总体结构、可行性分析与功能需求分析，并从角色和业务闭环角度展开用例分析。",
        119: "社区公益服务对接管理平台系统设计与实现。本章主要说明系统结构模块、业务流程、数据库存储设计以及核心页面实现，并重点展示与当前系统主线一致的关键功能。",
        123: "本系统采用前后端分离架构进行开发，以降低耦合度并提升协作效率。开发环境选用 Visual Studio Code（VS Code）作为统一工具；后端选用 Spring Boot 3 作为核心框架，数据持久层采用 MyBatis-Plus，数据库选用 MySQL 8.0；管理端采用 Vue 3 配合 Naive UI 组件库实现，移动端采用 Vue 3 配合 NutUI 构建 H5 页面；数据可视化引入 ECharts，前后端通过 Axios 以 RESTful API 方式通信。",
        134: "Spring Boot 3 是由 Spring 生态提供的企业级开发框架，能够通过自动配置、分层组织和成熟的中间件整合能力，显著提升后端业务开发效率。其与 Spring Security 的结合可较好支撑本系统中的 RBAC 权限控制、JWT 认证、审计留痕和社区范围访问控制等需求。",
        135: "2.3  Vue 3、Naive UI与NutUI",
        136: "Vue 3 具有组合式 API、响应式系统增强和良好的 TypeScript 支持，适合构建本系统这种同时包含管理端与移动端的前端工程。管理端采用 Naive UI 作为核心组件库，便于实现表格、筛选、弹窗、表单和数据看板等后台交互；移动端采用 NutUI 构建 H5 页面，适配触屏输入、卡片列表和底部导航等社区用户常见操作场景。",
        145: "本系统依据统一账号、多角色治理和社区数据隔离的业务需求进行总体规划，系统结构可划分为移动端用户模块、社区管理端模块、系统管理端模块和平台支撑模块四个部分。社区公益服务对接管理平台总体规划结构功能如图1所示。",
        148: "平台面向三类核心使用主体：发布求助的社区居民、通过认证后参与服务的志愿者，以及负责审核与治理的社区管理员。系统围绕“社区加入—需求发布—审核流转—服务认领—完成确认—评价反馈”的主流程展开，同时补充重点关怀对象管理、社区公告、便民信息、异常预警、AI 草稿辅助和数据看板等能力，形成较完整的社区公益服务与治理闭环。",
        154: "后端技术方面，Spring Boot 3 作为 Java 生态中成熟的应用开发框架，具备完善的自动配置能力和清晰的分层组织方式。MyBatis-Plus 提供了高效的数据访问封装，能够降低 CRUD 开发复杂度；MySQL 8.0 具备良好的事务处理能力、查询性能和 JSON 支持，能够满足本系统用户、需求、审核、评价和预警等核心数据的存储需要。Spring Security 为 RBAC 权限控制和 JWT 认证提供了成熟方案，使多角色访问控制和社区范围限制具备可实现性。",
        155: "前端技术方面，Vue 3 具备良好的组件化开发能力和响应式组织方式。管理端选用 Naive UI 组件库，便于快速构建审核列表、弹窗预览、权限管理和数据看板等后台页面；移动端选用 NutUI，更适合触屏端卡片、表单、标签筛选和底部导航等交互形式。ECharts 作为数据可视化工具，可满足后台统计看板和趋势分析的展示需求。",
        164: "目标用户群体方面，本系统主要包括普通居民、认证志愿者、社区管理员和系统管理员。移动端采用统一账号设计，普通用户完成注册后即可发布求助，后续通过志愿者认证扩展服务能力；重点关怀对象属于社区治理标签，而非独立登录角色。针对不同群体的操作特点，系统在移动端强调大按钮、短流程和状态反馈，在管理端强调筛选、审核和留痕能力。",
        165: "界面友好性方面，管理端基于 Naive UI 形成统一的后台交互风格，移动端基于 NutUI 形成轻量化触屏操作体验。关键操作均提供明确的按钮引导、状态提示和校验反馈，降低了居民、志愿者和管理员在高频业务中的操作成本。",
        173: "居民用户是社区公益服务的需求发起方，也是移动端的基础用户。系统采用统一账号设计，居民注册并加入社区后即可发布求助、查看需求进度、确认服务完成、评价志愿者、查看公告与便民信息，并可通过 AI 助手辅助整理求助内容。其用例如图2所示。",
        179: "志愿者用户并非独立账号体系，而是普通用户在通过志愿者认证后的能力扩展。其核心诉求是浏览社区内可服务需求、认领任务、更新服务进度、查看我的服务记录与接收评价反馈。志愿者用户的用例图如图3所示。",
        185: "社区管理员的核心职责是完成辖区治理闭环，主要功能包括：社区加入审核、公益需求审核、志愿者认证审核、重点关怀对象维护、社区公告与便民信息发布、异常预警处理以及辖区数据查看。社区管理员的用例图如图4所示。",
        191: "系统管理员负责平台级治理与监督，核心功能包括全局数据看板、区域与社区数据统筹、用户与权限管理、审计日志查看以及导出备份等支撑性操作，并在必要时具备社区管理员的管理能力。系统管理员的用例如图5所示。",
        209: "表现层通过 Axios 与业务逻辑层进行 RESTful API 通信，采用 JSON 格式传输数据。业务逻辑层通过 Service 接口协调需求、审核、认证、预警等业务规则，数据访问层通过 MyBatis-Plus 的 Mapper 接口操作数据库。这种分层架构有助于将移动端、管理端与后台治理逻辑解耦，便于后续维护与扩展。",
        211: "用户端功能模块包括：登录注册与社区加入、首页个人摘要、服务大厅、需求发布、我的需求、我的服务、服务评价、志愿者认证、社区公告、便民信息、AI 助手以及个人资料维护等模块。",
        218: "社区管理员端功能模块包括：社区数据看板、社区加入审核、需求审核、志愿者审核、服务过程监控、重点关怀对象管理、社区公告与便民信息维护、异常预警处理以及辖区用户查看等模块。",
        228: "系统管理员端功能模块包括：全局数据看板、区域与社区管理、用户与权限管理、审计日志、数据导出与备份等平台级治理功能，并可在权限范围内查看和协同处理社区管理端业务。",
        239: "公益需求状态流转模块是本系统最核心的业务流程之一。居民在移动端提交求助后，需求会经过审核、发布、认领、执行、确认和评价等多个状态节点，最终沉淀为可追溯的服务记录和治理数据。",
        240: "具体流程如下：居民发布需求后，记录进入“待审核”状态；社区管理员审核通过后，状态变为“待接单”；认证志愿者可在服务大厅浏览并认领需求，随后进入“已接单/服务中”状态；服务完成后，居民确认结果并进入评价阶段，双方的评价结果再反向更新志愿者服务画像与后台统计数据。",
        241: "该流程不仅实现了从求助发布到评价反馈的完整闭环，也为后续的服务质量追踪、重点对象关怀和异常预警识别提供了业务基础。",
        247: "数据库存储设计直接关系到系统的稳定性、可扩展性和后续治理能力。本系统采用 MySQL 8 作为核心数据库，结合 MyBatis-Plus 完成数据访问映射；数据库结构围绕统一账号、社区隔离、公益服务流转和后台治理四条主线展开。",
        249: "实体-关系模型用于描述系统中的用户、社区、公益需求、服务认领、服务评价、社区加入审核、志愿者认证、重点关怀对象和异常预警等核心实体及其联系。当前系统不再将求助者和志愿者拆分为两套用户表，而是以 sys_user 为账号中心，通过认证状态、社区归属和业务表关联来描述不同能力与角色。",
        250: "按照业务划分，系统数据库可分为用户与权限、社区治理、公益服务、内容发布和审计支撑等几类实体。抽象出的 E-R 关系图如图15所示。",
        256: "依据 schema_v2_prd.sql 的实际建表结果，当前系统数据库共包含 27 张表，覆盖账号体系、社区治理、公益服务、内容发布、预警留痕和平台支撑等数据对象。考虑论文篇幅限制，下面选取 7 张最能体现当前业务主线的核心数据表进行说明。",
        257: "用户表（sys_user）",
        258: "该表用于存储统一账号、角色、社区归属与加入状态等基础信息，是社区数据隔离和权限控制的核心。用户表结构如表1所示。",
        260: "社区加入申请表（community_join_application）",
        261: "该表记录用户通过邀请码提交的社区加入申请、审核结果和驳回原因，用于衔接“注册后未入社区”到“完成社区绑定”的治理流程。其结构如表2所示。",
        262: "志愿者认证信息表（volunteer_profile）",
        263: "该表用于保存志愿者认证状态、技能标签、服务半径、可服务时间和评分结果，是志愿服务能力建模的核心数据表。其结构如表3所示。",
        264: "重点关怀对象表（care_subject_profile）",
        265: "该表用于维护独居老人、残障居民等重点对象的关怀类型、关注等级、紧急联系人和监测开关，为主动关怀与异常预警提供基础数据。其结构如表4所示。",
        266: "公益服务需求表（service_request）",
        267: "该表用于记录居民发布的求助内容、服务类型、紧急程度、地址信息和审核状态，是整个公益服务流程的起点。其结构如表5所示。",
        268: "服务认领记录表（service_claim）",
        269: "该表记录志愿者接单时间、服务状态和服务时长等信息，用于衔接需求发布与服务执行过程。其结构如表6所示。",
        270: "服务评价表（service_evaluation）",
        271: "该表用于保存居民和志愿者在服务完成后的评价记录与评分结果，为服务质量追踪和志愿者画像更新提供依据。其结构如表7所示。",
        273: "本系统当前的核心页面围绕统一账号、社区绑定、公益服务流转与后台治理展开，主要包括登录注册与社区加入页、移动端首页、服务大厅页、我的需求页、我的服务页、服务评价页、志愿者认证页、社区公告与便民信息页、AI 助手页，以及管理端数据看板页、审核页、重点关怀对象与异常预警页、用户管理页和审计日志页。本节将围绕这些核心页面，分别介绍其页面布局与关键实现技术。",
        277: "登录页负责账号认证，注册页采集基础资料，社区加入页负责通过邀请码完成社区绑定。系统采用统一账号体系，用户注册后先进入普通用户视图，再根据后续认证状态扩展志愿服务能力。",
        278: "登录页主要提供账号/手机号/邮箱统一登录、密码显隐、忘记密码与去注册跳转等入口；注册页主要采集用户名、姓名、联系方式、验证码、密码和住址等基础信息，并支持手机注册与邮箱注册两种方式。",
        279: "社区加入页在登录后提供邀请码输入、校验预览和确认加入操作，用户可先核验社区名称，再提交绑定申请或直接完成加入。",
        280: "如果用户希望后续参与志愿服务，可在注册或资料完善阶段补充技能信息，但正式接单前仍需通过志愿者认证审核。",
        281: "页面整体采用分步卡片式布局，将“注册—登录—加入社区”串成连续流程，降低首次使用门槛。",
        282: "",
        283: "登录/注册页与社区加入页实现效果如图16所示。",
        289: "该组页面的关键在于“认证状态串联 + 社区绑定校验”。前端在注册成功后自动执行登录，并通过 hydrateUser() 同步最新用户信息；社区加入页则先调用邀请码校验接口，再根据结果完成社区绑定或申请提交流程。",
        290: "关键代码如下（节选）：",
        304: "// 注册提交流程：提交基础资料（可附带技能信息）-> 自动登录 -> 更新资料 -> 进入首页",
        322: "移动端首页用于集中展示个人资料、社区状态和互助入口，页面由顶部社区栏、个人摘要卡、勋章区和快捷操作区组成。用户可以在首页快速进入我的需求、我的服务、志愿者认证、便民信息、资料编辑和社区切换等功能。用户首页实现效果如图17所示。",
        327: "首页实现的核心是“状态聚合 + 组件拆分”。页面挂载时先刷新当前用户信息，再拉取用户看板摘要，用于同步社区名称、志愿服务统计和个人荣誉信息；顶部栏、摘要卡与快捷入口分别封装成独立组件，以便后续复用和维护。",
        345: "服务大厅页是移动端业务主入口，整合“我去帮助别人”和“我要发布求助”两类核心操作。页面由社区顶部栏、AI 输入框、快捷操作区、状态筛选区和任务列表区组成，用户可在同一页面切换查看已认领服务和已发布求助，并跳转到发布页或接单页。服务大厅与需求发布实现效果如图18所示。",
        349: "该部分的关键在于“并发加载 + 状态驱动渲染”。页面初始化通过 Promise.allSettled 并发获取首页统计、我的服务和我的求助数据；再通过 activeTab 与筛选条件切换列表内容，实现一套页面承载两条业务分支。",
        361: "（1）页面布局与实现",
        362: "我的需求页用于查看已发布求助的审核、接单、待确认与已完成状态；我的服务页用于查看个人已认领任务的执行进度；评价反馈页则在服务完成后提供星级评分和文字反馈入口，三者共同构成“发布后跟踪—执行中处理—完成后评价”的闭环。实现效果如图19所示。",
        365: "核心实现采用“状态筛选 + 详情弹层 + 评价提交”模式。我的需求和我的服务页面通过筛选条件变化自动刷新列表，评价页则基于 claimId 绑定订单上下文，并在提交期间通过 loading 状态防止重复操作。",
        366: "关键代码如下（节选）：",
        367: "// 我的需求：状态筛选变化后自动刷新列表",
        368: "onMounted(() => {",
        369: "  loadData('published')",
        370: "})",
        371: "watch([publishedStatusFilter, publishedSortFilter], () => {",
        372: "  loadData('published')",
        373: "})",
        374: "// 评价反馈：基于 claimId 绑定订单上下文",
        375: "async function submit() {",
        376: "  if (!claimId.value) return toast.error('缺少订单信息')",
        377: "  submitting.value = true",
        378: "  try {",
        379: "    const res = await api.post('/service-evaluation', {",
        380: "      claimId: claimId.value,",
        381: "      rating: Number(rating.value),",
        382: "      content: content.value.trim(),",
        383: "    })",
        384: "    if (res.code !== 200) throw new Error(res.message || '提交失败')",
        385: "    toast.success('评价已提交')",
        386: "    router.replace({ path: '/hall-overview', query: { kind: 'reviews' } })",
        387: "  } finally {",
        388: "    submitting.value = false",
        389: "  }",
        390: "}",
        393: "（1）页面布局与实现",
        394: "志愿者认证页用于将普通用户扩展为可接单的志愿服务角色。页面主要包括认证状态提示、技能标签选择、证件信息填写、服务半径设置和可服务时间填写等区域；若用户尚未加入社区，页面会先提示完成社区绑定。志愿者认证实现效果如图20所示。",
        395: "页面通过状态卡片展示“未认证、审核中、已认证、已驳回”等审核结果，用户可据此补充资料并重新提交申请。",
        398: "页面的关键实现是“认证状态回显 + 条件提交流程”。系统进入页面后先拉取当前用户的志愿者认证资料，并解析技能标签、审核状态和驳回原因；提交时会先校验社区归属，再统一组装认证申请参数。",
        399: "关键代码如下（节选）：",
        400: "// 提交志愿者认证前先校验社区归属",
        401: "async function submit() {",
        402: "  if (!canApply.value) {",
        403: "    toast.error('请先加入社区')",
        404: "    router.push('/join-community')",
        405: "    return",
        406: "  }",
        407: "  const skills = mergedSkills()",
        408: "  if (!skills.length) return toast.error('至少选择一项技能')",
        409: "  await applyVolunteerProfile({",
        410: "    idCardNo: form.idCardNo.trim() || undefined,",
        411: "    skillTags: skills,",
        412: "    serviceRadiusKm: Number(form.serviceRadiusKm || 3),",
        413: "    availableTime: form.availableTime.trim(),",
        414: "  })",
        415: "}",
        420: "社区公告与便民信息页分别承担“社区通知查看”和“生活服务查询”两类轻量信息服务。公告页按发布时间展示社区公告列表；便民信息页支持按分类筛选常用电话、医疗药店、维修服务和政务窗口等信息，并支持一键拨号。实现效果如图21所示。",
        425: "该部分的关键在于“按社区拉取 + 分类筛选”。页面会先同步当前用户社区信息，再调用公告和便民信息接口；公告列表按发布时间展示，便民信息页则根据 category 进行前端筛选和电话跳转。",
        426: "const res = await listConvenienceInfo()",
        427: "rows.value = res.code === 200 ? (res.data || []) : []",
        428: "const filteredRows = computed(() => !category.value || category.value === '全部' ? rows.value : rows.value.filter(x => x.category === category.value))",
        432: "AI 助手页用于辅助居民整理求助内容，而不是替代人工审核。页面采用对话式布局，支持快捷问题、自然语言输入和草稿卡片展示；当 AI 返回可用草稿后，用户可一键带入需求发布页继续补充。AI 助手页实现效果如图22所示。",
        436: "该页面的关键在于“对话上下文保留 + 草稿结构化输出”。前端会把最近若干轮消息整理为 history 传给 aiChat 接口；当返回结果包含需求草稿时，再将结构化数据写入本地缓存并跳转到需求发布页。",
        437: "关键代码如下（节选）：",
        438: "const res = await aiChat(text, history)",
        439: "chatRows.value.push({",
        440: "  role: 'ai',",
        441: "  text: res.data?.reply || '已收到。',",
        442: "  draft: res.data?.orderDraft,",
        443: "  analysisRecordId: res.data?.analysisRecordId,",
        444: "})",
        445: "saveAiDemandDraft({ analysisRecordId: row.analysisRecordId, inputText: row.sourceText, reply: row.text, draft: row.draft })",
        446: "router.push('/hall-publish')",
        452: "管理端数据看板页用于集中展示社区治理入口和关键业务概览。页面通过卡片方式聚合需求审核、志愿者审核、社区加入审核、重点关怀对象、便民信息、异常预警、用户管理和审计日志等入口，便于管理员快速进入高频治理场景。实现效果如图26所示。",
        457: "该页面的关键在于“治理入口聚合 + 角色范围控制”。社区管理员查看本辖区治理入口和统计信息，系统管理员则可进一步进入全局数据看板；前端通过统一卡片组件组织导航，后端根据当前角色控制统计数据范围。",
        458: "关键代码如下（节选）：",
        459: "// 角色范围控制 + 统计数据查询",
        460: "@GetMapping(\"/stats\")",
        461: "@PreAuthorize(\"hasAnyRole('COMMUNITY_ADMIN', 'SUPER_ADMIN')\")",
        462: "public Result<DashboardStatsVO> getStats() {",
        463: "    SysUser current = getCurrentUser();",
        464: "    Long scopeCommunityId = isCommunityAdmin(current) ? current.getCommunityId() : null;",
        465: "    DashboardStatsVO stats = dashboardService.getStats(scopeCommunityId);",
        466: "    return Result.success(stats);",
        467: "}",
        471: "社区加入审核、需求审核与志愿者审核页共同构成后台准入与流程把关模块。社区加入审核页用于确认居民归属社区；需求审核页用于决定公益需求是否进入发布状态；志愿者审核页用于校验志愿者资料并决定其是否具备接单资格。实现效果如图27所示。",
        477: "该组页面的关键实现是“统一审核动作 + 权限控制 + 预览核验”。前端通过数据表格、筛选条件和居中预览弹窗提升审核效率，后端则通过 DTO 封装审核参数，并限制只有社区管理员和系统管理员才能执行审核操作。",
        478: "// 需求审核接口（仅管理员角色）",
        479: "@PostMapping(\"/audit\")",
        480: "@PreAuthorize(\"hasAnyRole('COMMUNITY_ADMIN', 'SUPER_ADMIN')\")",
        481: "public Result<Void> auditRequest(@Valid @RequestBody ServiceRequestAuditDTO dto) {",
        482: "    Long auditorId = getCurrentUserId();",
        483: "    serviceRequestService.auditRequest(auditorId, dto);",
        484: "    String message = dto.getApproved() ? \"审核通过\" : \"已驳回\";",
        485: "    return Result.success(message, null);",
        486: "}",
        490: "重点关怀对象与异常预警页用于支撑社区主动治理。前者用于维护独居老人、残障居民等重点对象档案，记录关怀类型、等级和紧急联系人；后者用于汇总多日未登录、求助激增等异常事件，并支持管理员填写跟进结果。实现效果如图28所示。",
        495: "该部分的关键实现是“关怀档案结构化维护 + 预警闭环处理”。重点关怀对象页通过表单统一维护监测开关和紧急联系人；异常预警页通过状态筛选、详情预览和处理结果回填形成完整闭环。",
        496: "关键代码如下（节选）：",
        497: "const res = await alertEventList({",
        498: "  status: query.status ?? undefined,",
        499: "  page: query.page,",
        500: "  size: query.size,",
        501: "})",
        502: "rows.value = res.data.records || []",
        503: "total.value = res.data.total || 0",
        504: "const saveRes = await saveCareSubject({",
        505: "  userId: form.userId,",
        506: "  careType: form.careType,",
        507: "  careLevel: form.careLevel,",
        508: "  emergencyContactName: form.emergencyContactName,",
        509: "  emergencyContactPhone: form.emergencyContactPhone,",
        510: "  monitorEnabled: form.monitorEnabled,",
        511: "})",
        512: "if (saveRes.code === 200) load()",
        516: "用户管理与审计日志页分别承担平台账号治理与操作留痕查询功能。用户管理页支持按用户名、角色、状态和社区筛选账号，并提供新增、编辑、启用/禁用和导出操作；审计日志页则支持按时间、模块、风险等级和执行结果查询后台操作记录。实现效果如图29所示。",
        521: "该组页面的关键在于“条件查询 + 风险留痕”。用户管理页通过统一分页查询接口与角色、社区选项联动；审计日志页则将模块、成功状态和风险等级等字段结构化存储，以便后续追踪关键治理动作。",
        522: "关键代码如下（节选）：",
        523: "const res = await adminUserList({",
        524: "  username: query.username || undefined,",
        525: "  role: query.role ?? undefined,",
        526: "  status: query.status ?? undefined,",
        527: "  communityId: query.communityId ?? undefined,",
        528: "  page: query.page,",
        529: "  size: query.size,",
        530: "})",
        531: "const logRes = await auditLogList({",
        532: "  page: query.page,",
        533: "  size: query.size,",
        534: "  module: query.module || undefined,",
        535: "  success: query.success ?? undefined,",
        536: "  riskLevel: query.riskLevel ?? undefined,",
        537: "})",
        543: "本文围绕“社区公益服务对接管理平台”的建设目标，完成了从需求分析、系统设计到前后端实现与功能联调的完整过程。系统以“社区加入—居民求助—审核流转—志愿者认领—服务完成—评价反馈—异常预警”为主线，形成了面向真实社区治理场景的业务闭环。本小节归纳总结本文所做工作主要为以下几个方面：",
        544: "完成了系统总体方案设计与核心业务建模，围绕统一账号、社区绑定、公益需求流转、志愿者认证、重点关怀对象和异常预警等业务对象梳理了系统主线；",
        545: "完成了移动端与管理端的主要功能实现，移动端实现了登录注册、社区加入、首页、服务大厅、我的需求、我的服务、评价反馈、志愿者认证、社区公告、便民信息和 AI 助手等页面，管理端实现了数据看板、社区加入审核、需求审核、志愿者审核、重点关怀对象、异常预警、用户管理和审计日志等页面；",
        546: "完成了关键技术落地与系统联调，前端通过组件化、状态管理和多端页面拆分实现交互协同，后端通过分层架构、权限控制和数据访问封装支撑业务规则落地；",
        547: "形成了贴近基层治理场景的特色能力，系统通过 community_id 实现社区数据隔离，通过结构化审核和服务留痕提升过程可控性，并通过 AI 草稿辅助和异常预警增强平台的使用体验与治理支撑能力。",
        549: "社区公益服务对接管理平台已完成核心业务闭环设计，但在真实社区落地和治理深度方面仍有进一步优化空间。后续可重点从以下几个方向展开研究：",
        550: "（1）继续完善治理支撑能力。后续可进一步优化异常预警规则、重点关怀对象画像和志愿者推荐逻辑，并在 AI 辅助基础上增强需求分类、服务匹配和后台分析记录等能力，但仍应坚持“AI 辅助、人审决策”的原则。",
        551: "（2）增强真实社区接入能力。后续可结合更多真实社区数据源、地理位置能力和线下网格治理流程，提升社区归属校验、辖区联动和服务跟踪的准确性。",
        552: "（3）适度引入时间银行激励理念。后续可在现有积分机制基础上探索以服务时长为核心的激励模型，将“时间银行”作为社区互助可持续性的延伸研究方向，而非当前系统的核心业务模块。",
    }

    for raw_idx, text in para_updates.items():
        doc.paragraphs[mapped(raw_idx)].text = text

    table_rows = {
        4: [
            ["字段名称", "标识符", "数据类型", "说明"],
            ["id", "√", "bigint unsigned", "主键ID"],
            ["username", "-", "varchar(50)", "用户名（登录名）"],
            ["password_md5", "-", "varchar(100)", "密码哈希"],
            ["role", "-", "tinyint unsigned", "角色：超级管理员/社区管理员/普通用户"],
            ["identity_type", "-", "tinyint unsigned", "兼容字段：初始身份标记"],
            ["community_id", "-", "bigint unsigned", "所属社区ID"],
            ["community_join_status", "-", "tinyint unsigned", "社区加入状态"],
            ["real_name", "-", "varchar(50)", "真实姓名"],
            ["phone", "-", "varchar(20)", "联系电话"],
            ["email", "-", "varchar(100)", "邮箱"],
            ["address", "-", "varchar(255)", "常住地址"],
            ["time_coins", "-", "bigint", "兼容保留的时间币字段"],
            ["points", "-", "bigint", "累计积分"],
            ["skill_tags", "-", "json", "兼容保留的技能标签缓存"],
            ["status", "-", "tinyint unsigned", "账号状态：0禁用 1启用"],
            ["last_login_at", "-", "datetime(3)", "最近登录时间"],
            ["created_at", "-", "datetime(3)", "创建时间"],
        ],
        5: [
            ["字段名称", "标识符", "数据类型", "说明"],
            ["id", "√", "bigint unsigned", "主键ID"],
            ["user_id", "-", "bigint unsigned", "申请用户ID"],
            ["community_id", "-", "bigint unsigned", "申请加入社区ID"],
            ["invite_code", "-", "varchar(32)", "使用的邀请码"],
            ["real_name", "-", "varchar(50)", "申请人姓名"],
            ["phone", "-", "varchar(20)", "联系电话"],
            ["address", "-", "varchar(255)", "居住地址"],
            ["status", "-", "tinyint unsigned", "状态：待审核/通过/拒绝/撤回"],
            ["reviewer_user_id", "-", "bigint unsigned", "审核人ID"],
            ["reviewed_at", "-", "datetime(3)", "审核时间"],
            ["reject_reason", "-", "varchar(255)", "驳回原因"],
            ["created_at", "-", "datetime(3)", "创建时间"],
            ["updated_at", "-", "datetime(3)", "更新时间"],
            ["", "", "", ""],
        ],
        6: [
            ["字段名称", "标识符", "数据类型", "说明"],
            ["id", "√", "bigint unsigned", "主键ID"],
            ["user_id", "-", "bigint unsigned", "用户ID"],
            ["community_id", "-", "bigint unsigned", "所属社区ID"],
            ["cert_status", "-", "tinyint unsigned", "认证状态"],
            ["skill_tags", "-", "json", "技能标签集合"],
            ["service_radius_km", "-", "decimal(6,2)", "可服务半径"],
            ["available_time", "-", "varchar(255)", "可服务时间说明"],
            ["avg_rating", "-", "decimal(4,2)", "平均评分"],
            ["certified_at", "-", "datetime(3)", "认证通过时间"],
        ],
        7: [
            ["字段名称", "标识符", "数据类型", "说明"],
            ["id", "√", "bigint unsigned", "主键ID"],
            ["user_id", "-", "bigint unsigned", "用户ID"],
            ["community_id", "-", "bigint unsigned", "所属社区ID"],
            ["care_type", "-", "varchar(64)", "关怀类型"],
            ["care_level", "-", "tinyint unsigned", "关怀等级"],
            ["living_status", "-", "varchar(64)", "居住情况"],
            ["health_note", "-", "varchar(500)", "健康备注"],
            ["emergency_contact_name", "-", "varchar(64)", "紧急联系人姓名"],
            ["emergency_contact_phone", "-", "varchar(32)", "紧急联系人电话"],
            ["monitor_enabled", "-", "tinyint unsigned", "是否启用异常监测"],
        ],
        8: [
            ["字段名称", "标识符", "数据类型", "说明"],
            ["id", "√", "bigint unsigned", "主键ID"],
            ["requester_user_id", "-", "bigint unsigned", "需求发起人ID"],
            ["community_id", "-", "bigint unsigned", "所属社区ID"],
            ["service_type", "-", "varchar(50)", "服务类型"],
            ["description", "-", "text", "需求描述"],
            ["service_address", "-", "varchar(255)", "服务地址"],
            ["urgency_level", "-", "tinyint unsigned", "紧急程度"],
            ["status", "-", "tinyint unsigned", "状态：待审核至已完成"],
            ["audit_by_user_id", "-", "bigint unsigned", "审核人ID"],
        ],
        9: [
            ["字段名称", "标识符", "数据类型", "说明"],
            ["id", "√", "bigint unsigned", "主键ID"],
            ["request_id", "-", "bigint unsigned", "需求ID"],
            ["volunteer_user_id", "-", "bigint unsigned", "志愿者用户ID"],
            ["claim_status", "-", "tinyint unsigned", "认领状态"],
            ["claim_at", "-", "datetime(3)", "认领时间"],
        ],
        10: [
            ["字段名称", "标识符", "数据类型", "说明"],
            ["id", "√", "bigint unsigned", "主键ID"],
            ["claim_id", "-", "bigint unsigned", "认领记录ID"],
            ["request_id", "-", "bigint unsigned", "需求ID"],
            ["resident_user_id", "-", "bigint unsigned", "居民用户ID"],
            ["volunteer_user_id", "-", "bigint unsigned", "志愿者用户ID"],
            ["evaluator_role", "-", "tinyint unsigned", "评价方角色"],
            ["rating", "-", "tinyint unsigned", "评分：1-5"],
            ["content", "-", "varchar(500)", "评价内容"],
        ],
    }

    for table_idx, rows in table_rows.items():
        fill_table(doc.tables[table_idx], rows)

    doc.save(str(DOC_PATH))
    print(DOC_PATH)


if __name__ == "__main__":
    main()
