/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/ai-assistant': RouteRecordInfo<
      '/ai-assistant',
      '/ai-assistant',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/convenience-info': RouteRecordInfo<
      '/convenience-info',
      '/convenience-info',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'forgot-password': RouteRecordInfo<
      'forgot-password',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hall': RouteRecordInfo<
      '/hall',
      '/hall',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hall-overview': RouteRecordInfo<
      '/hall-overview',
      '/hall-overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hall-publish': RouteRecordInfo<
      '/hall-publish',
      '/hall-publish',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hall-take': RouteRecordInfo<
      '/hall-take',
      '/hall-take',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'join-community': RouteRecordInfo<
      'join-community',
      '/join-community',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/messages': RouteRecordInfo<
      '/messages',
      '/messages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notices': RouteRecordInfo<
      '/notices',
      '/notices',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'profile-edit': RouteRecordInfo<
      'profile-edit',
      '/profile-edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'register': RouteRecordInfo<
      'register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reload': RouteRecordInfo<
      'reload',
      '/reload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scan': RouteRecordInfo<
      '/scan',
      '/scan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/service-evaluate': RouteRecordInfo<
      '/service-evaluate',
      '/service-evaluate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/': RouteRecordInfo<
      '/user/',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'volunteer-certification': RouteRecordInfo<
      'volunteer-certification',
      '/volunteer-certification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/views/ai-assistant.vue': {
      routes:
        | '/ai-assistant'
      views:
        | never
    }
    'src/views/convenience-info.vue': {
      routes:
        | '/convenience-info'
      views:
        | never
    }
    'src/views/forgot-password.vue': {
      routes:
        | 'forgot-password'
      views:
        | never
    }
    'src/views/hall.vue': {
      routes:
        | '/hall'
      views:
        | never
    }
    'src/views/hall-overview.vue': {
      routes:
        | '/hall-overview'
      views:
        | never
    }
    'src/views/hall-publish.vue': {
      routes:
        | '/hall-publish'
      views:
        | never
    }
    'src/views/hall-take.vue': {
      routes:
        | '/hall-take'
      views:
        | never
    }
    'src/views/join-community.vue': {
      routes:
        | 'join-community'
      views:
        | never
    }
    'src/views/login.vue': {
      routes:
        | 'login'
      views:
        | never
    }
    'src/views/messages.vue': {
      routes:
        | '/messages'
      views:
        | never
    }
    'src/views/notices.vue': {
      routes:
        | '/notices'
      views:
        | never
    }
    'src/views/profile-edit.vue': {
      routes:
        | 'profile-edit'
      views:
        | never
    }
    'src/views/register.vue': {
      routes:
        | 'register'
      views:
        | never
    }
    'src/views/reload.vue': {
      routes:
        | 'reload'
      views:
        | never
    }
    'src/views/scan.vue': {
      routes:
        | '/scan'
      views:
        | never
    }
    'src/views/service-evaluate.vue': {
      routes:
        | '/service-evaluate'
      views:
        | never
    }
    'src/views/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/views/user/index.vue': {
      routes:
        | '/user/'
      views:
        | never
    }
    'src/views/volunteer-certification.vue': {
      routes:
        | 'volunteer-certification'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
